# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-20 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='file_path',
            field=models.FileField(upload_to='zip_files'),
        ),
    ]
