# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-21 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_auto_20160220_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='file_path',
            field=models.FileField(upload_to='uploaded_files'),
        ),
    ]
