# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-21 15:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_auto_20160221_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 2, 21, 15, 13, 48, 213198, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='deleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='modified',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 2, 21, 15, 13, 52, 281053, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
