# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-21 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_auto_20160221_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
